# Generated by Django 3.2.3 on 2021-05-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_score', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
