# Generated by Django 3.2.3 on 2021-05-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_score', '0003_auto_20210519_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='rolls_left',
            field=models.IntegerField(default=2),
        ),
    ]
